<?php
?>
<div class="oop">
    <h2>File List:</h2>
    <?php
    foreach ($block->getFileListObject()->giveFileList() as $filename) {
        echo "$filename \n" . 'Date of creation/change: ' . date('F d Y H:i:s.', filemtime($filename)) . "\n\n";
    }
    ?>
    <h2>Constants:</h2>
    <?php
    foreach ($block->getConstantsAndMethods()->getConstants() as $constant) {
        echo $constant . '<br/>';
    }
    ?>
    <h2>Methods:</h2>
    <?php
    foreach ($block->getMethods() as $method) {
        echo $method->name . '<br/>';
    }
    ?>
    <h2>Parameters:</h2>
    <?php foreach ($block->getParametersFromDi()->getParameters() as $parametersName => $parametersValue) :
        if (is_array($parametersValue)) {
            $parametersValue = $parametersValue['instance'] ?? 'array';
        }
        echo $parametersName . ' : ' . $parametersValue . '<br/>';
        ?>
    <?php endforeach; ?>
</div>