<div id="ko-hello-world" data-bind="scope:'ko-helloworld'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#ko-hello-world": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "ko-helloworld": {
                        "component": "BelodubrovskyiAn_MyTest/js/view/kojs",
                        "template" : "BelodubrovskyiAn_MyTest/kotmpl"
                    }
                }
            }
        }
    }
    </script>
</div>