<div class="custom link wishlist" data-bind="scope: 'wishlist'">
    <!-- ko if: wishlist().counter -->
    <span data-bind="text: wishlist().counter" class="counter qty"></span>
    <!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>