<?php
?>
<div id="knockout-lesson7-component"
     data-bind="scope:'knockout-lesson7-component'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#knockout-lesson7-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "knockout-lesson7-component": {
                        "component": "BelodubrovskyiAn_Lesson7Module/js/view/knockout-lesson7",
                        "template" : "BelodubrovskyiAn_Lesson7Module/knockout_lesson7_template"
                    }
                }
            }
        }
    }
    </script>
</div>