<div id="ko-hello-world" data-bind="scope:'geekhub-ko-helloworld'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#ko-hello-world": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "geekhub-ko-helloworld": {
                        "component": "BelodubrovskyiAn_Lesson7Module/js/view/lesson7",
                        "template" : "BelodubrovskyiAn_Lesson7Module/knockout_sample"
                    }
                }
            }
        }
    }
    </script>
</div>