<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
<div class="content-wrapper-test-for-prepare-layout">
    <h1>
        <span>This template setting from prepareLayout</span>
    </h1>
    <?php if ($block->getName()):?>
        <h3>
            <?= /* @escapeNotVerified */ $block->getName(); ?>
        </h3>
    <?php endif;?>
    <?php if ($block->getLastName()):?>
        <h3>
            <?= /* @escapeNotVerified */ $block->getLastName(); ?>
        </h3>
    <?php endif;?>
    <a href="<?=  $block->getUrlToJsonResponse(); ?>">Link to JSON controller</a>
</div>