<?php
namespace display_constants;

class DisplayConstantsAndMethods
{
    const NONE = 0;
    const REQUEST = 100;
    const AUTH = 101;

    /**
     * @return int
     */
    public function firstMethod()
    {
        return 5;
    }

    /**
     * @return string
     */
    final function secondMethod()
    {
        return 'second';
    }

    /**
     * @return bool
     */
    private static function thirdMethod()
    {
        return true;
    }

    public function getConstants()
    {
        $oClass = new \ReflectionClass(__CLASS__);
        return $oClass->getConstants();
    }

    public function getMethods()
    {
        $class = new \ReflectionClass(__CLASS__);
        return $class->getMethods();
    }
}
//
//$foo = new DisplayConstantsAndMethods();
//
//print_r($foo->getConstants());
//print_r($foo->getMethods());

