<?php /** @var \BelodubrovskyiAn\AskQuestion\Block\Questions $block */
$questions = $block->getQuestions();
?>
<?php if ($questions->count()): ?>
    <h2>Questions from customers:</h2>
    <ol>
        <?php /** @var \BelodubrovskyiAn\AskQuestion\Model\AskQuestion $askQuestion */
        foreach ($questions as $question):
            ?>
            <li>
                <?= __('From <b>%1</b>: %2', $question->getName(), $question->getQuestion()) ?>
            </li>
        <?php endforeach; ?>
    </ol>
<?php endif; ?>
