<?php /** @var \BelodubrovskyiAn\AskQuestion\Block\Questions $block */
$questions = $block->getQuestions();
?>
<?php if ($questions->count()): ?>
    <ul>
        <?php /** @var \BelodubrovskyiAn\AskQuestion\Model\AskQuestion $askQuestion */
        foreach ($questions as $question):
            ?>
            <li><?= __('Question : %1', $question->getQuestion()) ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>